# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 20:57


from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('kicked', 'Kicked to attorney general'), ('denied', 'Denied by attorney general'), ('relatg', 'Released by attorney general'), ('relagc', 'Released by agency')], max_length=2)),
                ('amount_asked', models.PositiveIntegerField(null=True)),
                ('amount_paid', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'FOIA',
                'verbose_name_plural': 'FOIAs',
            },
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('raw', models.TextField()),
                ('text', models.TextField()),
                ('html', models.TextField(verbose_name='HTML')),
                ('sent', models.DateTimeField()),
                ('processed', models.BooleanField(default=False, editable=False)),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('rolodex_person_id', models.PositiveSmallIntegerField(null=True)),
                ('rolodex_contact_id', models.PositiveSmallIntegerField(null=True)),
                ('rolodex_organization_id', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='recipients',
            field=models.ManyToManyField(to='foiatracker.Recipient'),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foiatracker.Sender'),
        ),
        migrations.AddField(
            model_name='foia',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foiatracker.InboundEmail'),
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foiatracker.InboundEmail'),
        ),
        migrations.AddField(
            model_name='event',
            name='foia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foiatracker.Foia'),
        ),
    ]
