# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 21:53


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0002_auto_20160406_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amount_asked',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='amount_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='foiatracker.InboundEmail'),
        ),
    ]
