# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 14:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0005_auto_20160412_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foia',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
