# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 19:06


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0006_auto_20160413_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='name',
        ),
        migrations.AddField(
            model_name='sender',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sender',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foiatracker.InboundEmail'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting agency response'), ('kicked', 'Kicked to attorney general'), ('denied', 'Denied by attorney general'), ('relatg', 'Released by attorney general'), ('relagc', 'Released by agency')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='foia',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foiatracker.InboundEmail'),
        ),
    ]
