# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 19:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0007_auto_20160413_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='foia',
            name='reminder_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foia',
            name='reminder_sent_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
