# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 20:04


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0009_auto_20160413_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('sent_time', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='foia',
            name='reminder_scheduled_time',
        ),
        migrations.RemoveField(
            model_name='foia',
            name='reminder_sent_time',
        ),
        migrations.AddField(
            model_name='reminder',
            name='foia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foiatracker.Foia'),
        ),
    ]
