# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 22:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0010_auto_20160413_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='foia',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
