# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 18:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0011_foia_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
