# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 16:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0012_auto_20160421_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='foia',
            name='subject',
            field=models.CharField(default='Subject', help_text='Example: Dallas ISD annual audit', max_length=255),
            preserve_default=False,
        ),
    ]
