# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 17:46


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0013_foia_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foia',
            old_name='subject',
            new_name='request_subject',
        ),
        migrations.AlterField(
            model_name='event',
            name='foia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foiatracker.Foia'),
        ),
    ]
