# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 20:00


import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0015_auto_20160422_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-update_date']},
        ),
        migrations.AlterField(
            model_name='event',
            name='update_date',
            field=models.DateField(default=datetime.date(2016, 4, 22)),
            preserve_default=False,
        ),
    ]
