# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 14:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0017_auto_20160422_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundemail',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='foiatracker.Recipient'),
        ),
    ]
