# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 16:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0018_auto_20160502_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foia',
            options={'ordering': ['-sent'], 'verbose_name': 'FOIA', 'verbose_name_plural': 'FOIAs'},
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting agency response'), ('kicked', 'Kicked to attorney general'), ('denied', 'Denied by attorney general'), ('relatg', 'Released by attorney general'), ('relagc', 'Released by agency'), ('wthdrwn', 'Withdrawn')], default='pending', max_length=7),
        ),
    ]
