# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-01 19:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0019_auto_20160615_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting agency response'), ('kicked', 'Kicked to attorney general'), ('denied', 'Denied by attorney general'), ('relatg', 'Released by attorney general'), ('relagc', 'Released by agency'), ('norecs', 'No responsive records'), ('wthdrwn', 'Withdrawn')], default='pending', max_length=7),
        ),
    ]
