# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 19:21


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0020_auto_20160801_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored_file', models.FileField(upload_to='foiatracker_attachments/%Y/%m/')),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foiatracker.InboundEmail')),
            ],
        ),
    ]
