# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 19:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0021_emailattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
