# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 16:24


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0024_auto_20170323_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('collaborators', models.ManyToManyField(related_name='projects', to='foiatracker.Sender')),
            ],
        ),
        migrations.AddField(
            model_name='foia',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foiatracker.Project'),
        ),
    ]
