# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 20:05


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0028_auto_20170324_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['email']},
        ),
    ]
