# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 17:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0030_auto_20170330_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
