# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 20:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0032_auto_20170411_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting agency response'), ('kicked', 'Kicked to attorney general'), ('denied', 'Denied by attorney general'), ('relatg', 'Released by attorney general'), ('paragc', 'Partially released by agency'), ('relagc', 'Released by agency'), ('norecs', 'No responsive records'), ('wthdrwn', 'Withdrawn')], default='pending', max_length=7),
        ),
    ]
