# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 23:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0033_auto_20170712_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sender',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
