# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiatracker', '0034_auto_20180108_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='foia',
            name='agency_id',
            field=models.CharField(blank=True, help_text="The agency's internal ID number for this request", max_length=20),
        ),
    ]
